# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 05:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='position',
        ),
        migrations.AddField(
            model_name='member',
            name='nickname',
            field=models.CharField(default='프로듀스101', max_length=9),
        ),
        migrations.AddField(
            model_name='member',
            name='url',
            field=models.TextField(default='http://www.wannaonego.com', validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(default='워너원', max_length=9),
        ),
    ]
